// Themed word lists — 30-40 common words per category
// All 4-8 letters, UK spellings, suitable for elderly UK audience
const WORD_LISTS = {
  "Animals": [
    "BEAR", "CATS", "DEER", "DOGS", "DUCK", "FROG", "GOAT", "HARE",
    "LAMB", "LION", "MOLE", "NEWT", "PONY", "SEAL", "SWAN", "TOAD",
    "WOLF", "HORSE", "MOUSE", "OTTER", "PANDA", "SHEEP", "SNAKE",
    "TIGER", "WHALE", "ZEBRA", "BADGER", "DONKEY", "FERRET", "GERBIL",
    "JAGUAR", "KITTEN", "MONKEY", "RABBIT", "WALRUS", "HAMSTER",
    "GORILLA", "PANTHER", "DOLPHIN", "PENGUIN"
  ],
  "Birds": [
    "CROW", "DOVE", "DUCK", "GULL", "HAWK", "HENS", "LARK", "OWLS",
    "SWAN", "WREN", "CRANE", "EAGLE", "FINCH", "GOOSE", "HERON",
    "MACAW", "RAVEN", "ROBIN", "STORK", "SWIFT", "FALCON", "MAGPIE",
    "PARROT", "PIGEON", "PUFFIN", "THRUSH", "TOUCAN", "TURKEY",
    "OSPREY", "CUCKOO", "MARTIN", "PLOVER", "LINNET", "GROUSE",
    "PETREL", "GANNET", "DIPPER", "DUNLIN"
  ],
  "Sea Life": [
    "BASS", "CLAM", "CRAB", "DACE", "EELS", "FISH", "PIKE", "SEAL",
    "CARP", "TUNA", "CORAL", "PRAWN", "SHARK", "SQUID", "TROUT",
    "WHALE", "CONGER", "MUSSEL", "OYSTER", "SALMON", "SHRIMP",
    "TURBOT", "WHELK", "PLAICE", "KIPPER", "MARLIN", "MULLET",
    "TURTLE", "URCHIN", "WALRUS", "HALIBUT", "HERRING", "LOBSTER",
    "MACKEREL", "OCTOPUS", "SARDINE", "DOLPHIN"
  ],
  "Insects": [
    "ANTS", "BEES", "FLEA", "GNAT", "MITE", "MOTH", "TICK", "WASP",
    "APHID", "CRANE", "FLIES", "LOUSE", "MIDGE", "BEETLE", "CICADA",
    "EARWIG", "HORNET", "LOCUST", "MANTIS", "MAYFLY", "SAWFLY",
    "WEEVIL", "CRICKET", "FIREFLY", "LADYBIRD", "TERMITE",
    "MONARCH", "BLUEBOTTLE", "HOVERFLY", "GREENFLY", "BLACKFLY",
    "SANDFLY", "GADFLY", "BOTFLY", "NYMPH"
  ],
  "Fruit": [
    "DATE", "FIGS", "KIWI", "LIME", "PEAR", "PLUM", "APPLE", "GRAPE",
    "GUAVA", "LEMON", "MANGO", "MELON", "OLIVE", "PEACH", "BERRY",
    "BANANA", "CHERRY", "DAMSON", "LYCHEE", "ORANGE", "PAPAYA",
    "QUINCE", "RAISIN", "SULTANA", "APRICOT", "AVOCADO", "COCONUT",
    "CURRANT", "KUMQUAT", "SATSUMA", "RHUBARB", "CONKER",
    "NECTARINE", "BRAMBLE", "SLOE", "PRUNE", "MEDLAR"
  ],
  "Vegetables": [
    "BEAN", "CORN", "KALE", "LEEK", "PEAS", "SAGE", "YAMS", "CHARD",
    "CRESS", "ONION", "SWEDE", "BASIL", "THYME", "TURNIP", "CARROT",
    "CELERY", "GARLIC", "GINGER", "LENTIL", "MARROW", "FENNEL",
    "PEPPER", "POTATO", "RADISH", "ROCKET", "SORREL", "SPROUT",
    "SQUASH", "TOMATO", "ENDIVE", "CHICORY", "CABBAGE", "LETTUCE",
    "PARSLEY", "PARSNIP", "SHALLOT", "SPINACH"
  ],
  "Cooking": [
    "BAKE", "BOIL", "CHOP", "DICE", "FOLD", "FLAN", "GRILL", "HEAT",
    "KNEAD", "MINCE", "POACH", "ROAST", "SAUCE", "SAUTE", "SIMMER",
    "SLICE", "STEAM", "STEW", "TOAST", "WHISK", "BLEND", "BRAISE",
    "CREAM", "CRUST", "DOUGH", "GLAZE", "GRAVY", "LADLE", "MARINADE",
    "PASTRY", "RECIPE", "SIEVE", "STOCK", "BATTER", "BLANCH",
    "FILLET", "SEASON", "SPREAD"
  ],
  "Drinks": [
    "ALE", "GIN", "RUM", "TEA", "BEER", "BREW", "CIDER", "COCOA",
    "COLA", "JUICE", "LAGER", "MILK", "PORT", "STOUT", "TODDY",
    "TONIC", "VODKA", "WATER", "WINE", "BRANDY", "COFFEE", "COGNAC",
    "SQUASH", "WHISKY", "SHERRY", "SHANDY", "MEAD", "PUNCH",
    "NECTAR", "LATTE", "MOCHA", "CIDER", "BITTER", "CORDIAL",
    "MERLOT", "CLARET"
  ],
  "Colours": [
    "AQUA", "BLUE", "BUFF", "CYAN", "DRAB", "FAWN", "GOLD", "GREY",
    "JADE", "LIME", "NAVY", "PINK", "PLUM", "ROSE", "RUBY", "RUST",
    "SAGE", "SAND", "TEAL", "AMBER", "BEIGE", "BLACK", "BROWN",
    "CORAL", "CREAM", "GREEN", "IVORY", "KHAKI", "LEMON", "LILAC",
    "MAUVE", "OLIVE", "PEACH", "TAUPE", "WHITE", "COPPER", "INDIGO",
    "MAROON", "ORANGE", "PURPLE", "SCARLET", "SILVER", "VIOLET",
    "YELLOW"
  ],
  "Weather": [
    "CALM", "COLD", "COOL", "DAMP", "DEWY", "DULL", "FAIR", "GALE",
    "GUST", "HAIL", "HAZE", "HEAT", "MILD", "MIST", "RAIN", "SMOG",
    "SNOW", "WARM", "WIND", "BALMY", "BLAST", "CLEAR", "CLOUD",
    "FLOOD", "FOGGY", "FROST", "HUMID", "MISTY", "RAINY", "SLEET",
    "SNOWY", "STORM", "SUNNY", "WINDY", "BREEZE", "CHILL", "DRIZZLE",
    "FREEZE", "SHOWER", "SQUALL", "THAW", "THUNDER"
  ],
  "Flowers": [
    "IRIS", "LILY", "ROSE", "ASTER", "DAISY", "LUPIN", "PANSY",
    "PEONY", "POPPY", "STOCK", "TULIP", "VIOLA", "ORCHID", "CROCUS",
    "DAHLIA", "AZALEA", "CLOVER", "HYSSOP", "JASMINE", "MALLOW",
    "VIOLET", "ZINNIA", "DAPHNE", "FREESIA", "LOBELIA", "NIGELLA",
    "PRIMULA", "COWSLIP", "HEATHER", "CAMPION", "FUCHSIA",
    "HONESTY", "LAVENDER", "PETUNIA", "SWEET PEA", "BLOSSOM",
    "THISTLE", "FOXGLOVE"
  ],
  "Trees": [
    "ASH", "BAY", "BOX", "ELM", "FIR", "OAK", "YEW", "ACER",
    "BIRCH", "CEDAR", "ELDER", "HOLLY", "LARCH", "MAPLE", "OLIVE",
    "PLANE", "ROWAN", "BEECH", "HAZEL", "LIME", "PINE", "PLUM",
    "THORN", "CHERRY", "CHESTNUT", "CONIFER", "CYPRESS", "JUNIPER",
    "POPLAR", "SPRUCE", "SYCAMORE", "WALNUT", "WILLOW", "LAUREL",
    "LINDEN", "DAMSON", "REDWOOD", "MAGNOLIA"
  ],
  "Clothing": [
    "BELT", "CAPE", "COAT", "GOWN", "HATS", "HOOD", "KILT", "MITT",
    "ROBE", "SASH", "SLIP", "SOCK", "VEST", "WRAP", "APRON", "BERET",
    "BOOTS", "CLOAK", "DRESS", "GLOVE", "JEANS", "SCARF", "SHAWL",
    "SHIRT", "SHOES", "SKIRT", "SMOCK", "STOLE", "TUNIC", "BLOUSE",
    "BONNET", "BRACES", "CRAVAT", "JACKET", "JUMPER", "SANDAL",
    "TIGHTS", "ANORAK", "FLEECE", "BLAZER", "CARDIGAN"
  ],
  "Kitchen": [
    "BOWL", "CUPS", "DISH", "FORK", "GRILL", "LADLE", "KNIFE",
    "OVEN", "PAIL", "PANS", "RACK", "SINK", "TAPS", "TRAY", "BASIN",
    "BOARD", "CLOTH", "FLASK", "GLASS", "KETTLE", "MIXER", "PLATE",
    "SCALES", "SIEVE", "SPOON", "STOVE", "TIMER", "TONGS",
    "COOKER", "FUNNEL", "GRATER", "JUICER", "MASHER", "SAUCER",
    "TEAPOT", "TUREEN", "COLANDER", "TOASTER"
  ],
  "Furniture": [
    "BARS", "BATH", "BEDS", "BUNK", "DESK", "LAMP", "RACK", "RUGS",
    "SEAT", "SOFA", "BENCH", "CHAIR", "CHEST", "COUCH", "DIVAN",
    "SHELF", "STOOL", "TABLE", "TRUNK", "BUREAU", "BUNKER", "CARPET",
    "CRADLE", "CUPBOARD", "DRAWER", "MIRROR", "PILLOW",
    "SCREEN", "SETTEE", "BUREAU", "CABINET", "CUSHION", "DRESSER",
    "HAMMOCK", "OTTOMAN", "WARDROBE"
  ],
  "Tools": [
    "AWL", "AXE", "BIT", "FILE", "FORK", "JACK", "MALLET", "NAIL",
    "PICK", "RAKE", "RULE", "SAWS", "VICE", "BRACE", "BRUSH",
    "CHISEL", "CLAMP", "DRILL", "GAUGE", "KNIFE", "LATHE", "LEVEL",
    "PLANE", "PLUMB", "PUNCH", "RULER", "SPADE", "TROWEL", "WRENCH",
    "HAMMER", "LADDER", "PLIERS", "SANDER", "SHEARS", "SPANNER",
    "GIMLET", "HACKSAW", "MALLET"
  ],
  "Countries": [
    "CUBA", "FIJI", "IRAN", "IRAQ", "LAOS", "MALI", "OMAN", "PERU",
    "CHAD", "CHILE", "CHINA", "EGYPT", "FRANCE", "GHANA", "GREECE",
    "INDIA", "ITALY", "JAPAN", "KENYA", "LIBYA", "MALTA", "NEPAL",
    "NIGER", "NORWAY", "POLAND", "QATAR", "SPAIN", "SUDAN", "SYRIA",
    "TONGA", "TURKEY", "WALES", "ZAMBIA", "BRAZIL", "CANADA",
    "CYPRUS", "ICELAND", "IRELAND", "MOROCCO", "SWEDEN"
  ],
  "Cities": [
    "BATH", "CORK", "HULL", "YORK", "BAKU", "BONN", "KIEV", "LIMA",
    "OSLO", "RIGA", "ROME", "DERBY", "DOVER", "LEEDS", "PERTH",
    "TOKYO", "TRURO", "WELLS", "BERLIN", "BOSTON", "DUBLIN", "DUNDEE",
    "EXETER", "LISBON", "LONDON", "MADRID", "MALAGA", "MOSCOW",
    "NAPLES", "OXFORD", "PARIS", "PRAGUE", "VENICE", "VIENNA",
    "ZURICH", "CARDIFF", "CHESTER", "DURHAM", "NORWICH", "LINCOLN"
  ],
  "Sports": [
    "DARTS", "GOLF", "JUDO", "POLO", "RUGBY", "BOWLS", "BOXING",
    "CHESS", "DIVING", "FENCING", "HOCKEY", "NETBALL", "RACING",
    "RIDING", "ROWING", "SAILING", "SKIING", "SOCCER", "SQUASH",
    "TENNIS", "ARCHERY", "CRICKET", "CROQUET", "CYCLING", "FISHING",
    "HURDLES", "JAVELIN", "JUMPING", "KARATE", "RUNNING", "SURFING",
    "WALKING", "SNOOKER", "CURLING", "DISCUS", "SHOT PUT"
  ],
  "Music": [
    "BASS", "BEAT", "DRUM", "DUET", "FIFE", "GONG", "HARP", "HORN",
    "HYMN", "JAZZ", "LUTE", "NOTE", "OBOE", "SONG", "TRIO", "TUBA",
    "TUNE", "BANJO", "BUGLE", "CAROL", "CELLO", "CHORD", "CHOIR",
    "FLUTE", "MARCH", "MUSIC", "OPERA", "ORGAN", "PIANO", "PIPES",
    "POLKA", "VIOLA", "WALTZ", "FIDDLE", "GUITAR", "MELODY",
    "RHYTHM", "SONATA", "BALLAD", "CORNET"
  ],
  "Body": [
    "ARCH", "BACK", "BONE", "CALF", "CHIN", "EARS", "EYES", "FEET",
    "GUMS", "HAIR", "HAND", "HEAD", "HEEL", "HIPS", "JAWS", "KNEE",
    "LEGS", "LIPS", "LUNG", "NAIL", "NECK", "NOSE", "PALM", "RIBS",
    "SHIN", "SKIN", "TOES", "ANKLE", "BROW", "CHEEK", "CHEST",
    "ELBOW", "HEART", "MOUTH", "SKULL", "SPINE", "THIGH", "THUMB",
    "WAIST", "WRIST"
  ],
  "Family": [
    "AUNT", "BABY", "BOYS", "CLAN", "GIRL", "HEIR", "KIDS", "LADY",
    "MALE", "MAMA", "MATE", "PAPA", "TWIN", "WIFE", "BRIDE", "CHILD",
    "ELDER", "GROOM", "MUMMY", "NANNY", "NIECE", "UNCLE", "WOMAN",
    "YOUTH", "COUSIN", "DADDY", "FAMILY", "FATHER", "GRANNY",
    "INFANT", "MOTHER", "NEPHEW", "PARENT", "SISTER", "SPOUSE",
    "BROTHER", "GRANDMA", "GRANDPA", "HUSBAND", "TODDLER"
  ],
  "Jobs": [
    "CHEF", "MAID", "MONK", "NURSE", "PAGE", "POET", "BAKER",
    "CLERK", "GUIDE", "JUDGE", "MASON", "MAYOR", "MINER", "PILOT",
    "TUTOR", "VICAR", "ARTIST", "BARBER", "BISHOP", "BUTLER",
    "DANCER", "DOCTOR", "DRIVER", "FARMER", "GROCER", "JOCKEY",
    "JOINER", "MATRON", "MILLER", "PORTER", "POTTER", "SAILOR",
    "SINGER", "TAILOR", "WARDEN", "WEAVER", "BUILDER", "CHEMIST",
    "DENTIST", "FLORIST", "PLUMBER", "SOLDIER"
  ],
  "Transport": [
    "BIKE", "BOAT", "BRIG", "BUSS", "CART", "CARS", "JEEP", "RAFT",
    "SHIP", "SLED", "TAXI", "TRAM", "VANS", "CANOE", "COACH",
    "FERRY", "KAYAK", "LORRY", "PLANE", "PUNT", "TRAIN", "TRUCK",
    "YACHT", "BARROW", "LAUNCH", "PADDLE", "ROCKET", "SLEIGH",
    "TANKER", "VESSEL", "GLIDER", "BARGE", "DINGHY", "LINER",
    "HANSOM", "SALOON", "ESTATE", "STEAMER"
  ],
  "Gems & Stones": [
    "AGATE", "AMBER", "BERYL", "CORAL", "FLINT", "IVORY", "JADE",
    "JEWEL", "LAPIS", "ONYX", "OPAL", "PEARL", "RUBY", "SLATE",
    "TOPAZ", "BASALT", "COBALT", "GARNET", "GNEISS", "GRAVEL",
    "JASPER", "MARBLE", "PUMICE", "QUARTZ", "SCHIST", "ZIRCON",
    "CRYSTAL", "DIAMOND", "EMERALD", "GRANITE", "OBSIDIAN",
    "PEBBLE", "SANDSTONE", "SAPPHIRE"
  ],
  "Fabrics": [
    "CORD", "FELT", "FUR", "JUTE", "LACE", "LAWN", "SILK", "WOOL",
    "BAIZE", "CRAPE", "DENIM", "GAUZE", "LINEN", "LYCRA", "NYLON",
    "PLAID", "RAYON", "SATIN", "SERGE", "SUEDE", "TARTAN", "TULLE",
    "TWEED", "TWILL", "VOILE", "CALICO", "CANVAS", "CHINTZ",
    "COTTON", "DAMASK", "FLEECE", "JERSEY", "MUSLIN", "VELVET",
    "RIBBON", "BURLAP", "MOHAIR", "CHIFFON", "TAFFETA"
  ],
  "Garden": [
    "ARCH", "BEDS", "BULB", "CLAY", "FORK", "GATE", "HERB", "HOSE",
    "LAWN", "LOAM", "MOSS", "PATH", "PEAT", "POND", "ROOT", "SEED",
    "SHED", "SOIL", "VINE", "WEED", "BLOOM", "FENCE", "FRUIT",
    "GRASS", "HEDGE", "MULCH", "PLANT", "SHRUB", "SPADE", "THORN",
    "BORDER", "CLOCHE", "COMPOST", "FLOWER", "GRAVEL", "PAVING",
    "TRELLIS", "PRUNER", "MANURE", "DIBBER"
  ],
  "Sweets & Treats": [
    "BUNS", "CAKE", "FLAN", "ICES", "MINT", "TART", "CANDY", "CREAM",
    "FUDGE", "JELLY", "SCONE", "SWEET", "TORTE", "WAFER", "BONBON",
    "COOKIE", "CRUMBLE", "ECLAIR", "GATEAU", "MERINGUE", "MUFFIN",
    "NOUGAT", "PASTRY", "SPONGE", "SUNDAE", "TOFFEE", "TREACLE",
    "TRUFFLE", "BROWNIE", "CARAMEL", "CUSTARD", "FONDANT",
    "LOLLIPOP", "PANCAKE", "PAVLOVA", "PUDDING", "SHERBET",
    "CRUMPET", "BISCUIT"
  ]
};
